// This file is automatically generated by Citron version 1.0.
//
// The parser class defined below conforms to the CitronParser protocol
// defined in CitronParser.swift. 
// 
// The authors of Citron disclaim copyright to the source code in this file.

// Preface


    enum Token {
        case keyword // for let, rec, int ..
        case punctuation // for (, ) ..
        case identifier(String) // for IDENTIFIER
        case integerLiteral(Int)
        case floatLiteral(Double)
        case boolLiteral(Bool)
    }

    extension Token {
        func asInt() -> Int { 
          switch self {
            case let .integerLiteral(i):
              return i
            default:
              fatalError("\(self) is not integer value.")
          }
        }

        func asFloat() -> Double { 
          switch self {
            case let .floatLiteral(f):
              return f
            default:
              fatalError("\(self) is not float value.")
          }
        }

        func asBool() -> Bool {
          switch self {
            case let .boolLiteral(b):
             return b
            default:
             fatalError("\(self) is not boolean value.")
          }
        }

        func asIdentifier() -> String {
          switch self {
            case let .identifier(id):
             return id
            default:
             fatalError("\(self) is not identifier.")
          }
        }
    }


// Parser class

import CitronKit

class Parser: CitronParser {

    // Types

    typealias CitronSymbolCode = UInt8
    typealias CitronStateNumber = UInt8
    typealias CitronRuleNumber = UInt8

    enum CitronTokenCode: CitronSymbolCode {
      case ADD                            =   1
      case SUB                            =   2
      case MUL                            =   3
      case DIV                            =   4
      case INT                            =   5
      case FLOAT                          =   6
      case BOOL                           =   7
      case IDENTIFIER                     =   8
    }

    typealias CitronToken = Token

    enum CitronSymbol {
        case yyBaseOfStack
        case yy0(CitronToken)
        case yy8(Const)
        case yy12(Expr)
    }

    typealias CitronResult = Expr

    // Counts

    let yyNumberOfSymbols: Int = 12
    let yyNumberOfStates: Int = 8

    // Action tables

    let yyLookaheadAction: [(CitronSymbolCode, CitronParsingAction)] = [
/*   0 */  ( 0, .RD( 0)), ( 1, .SH( 4)), ( 2, .SH( 3)), ( 3, .SH( 2)), ( 4, .SH( 1)),
/*   5 */  (12, .RD( 2)), ( 5, .SR( 6)), ( 6, .SR( 7)), ( 7, .SR( 8)), ( 8, .SR( 9)),
/*  10 */  (12, .RD( 2)), ( 9, .ACCEPT),   (10, .SH( 5)), (11, .RD( 5)), (10, .RD( 4)),
/*  15 */  (11, .RD( 5)), (12, .RD( 2)), (10, .RD( 3)), (11, .RD( 5)), (10, .SH( 6)),
/*  20 */  (11, .RD( 5)), (12, .RD( 2)), (10, .SH( 7)), (11, .RD( 5)), ( 3, .SH( 2)),
/*  25 */  ( 4, .SH( 1)),
    ]

    let yyShiftUseDefault: Int = 26
    let yyShiftOffsetMin: Int = 0
    let yyShiftOffsetMax: Int = 21
    let yyShiftOffset: [Int] = [
        /*     0 */     1,    1,    1,    1,    1,    0,   21,   21,
    ]

    let yyReduceUseDefault: Int = -1
    let yyReduceOffsetMin: Int =   0
    let yyReduceOffsetMax: Int =   12
    let yyReduceOffset: [Int] = [
        /*     0 */     2,    4,    7,    9,   12,
    ]

    let yyDefaultAction: [CitronParsingAction] = [
  /*     0 */  .ERROR , .ERROR , .ERROR , .ERROR , .ERROR ,
  /*     5 */  .ERROR , .RD( 2), .RD( 1),
    ]

    // Fallback

    let yyHasFallback: Bool = false
    let yyFallback: [CitronSymbolCode] = []

    // Wildcard

    let yyWildcard: CitronSymbolCode? = nil

    // Rules

    let yyRuleInfo: [(lhs: CitronSymbolCode, nrhs: UInt)] = [
        (lhs: 9, nrhs: 1),
        (lhs: 10, nrhs: 3),
        (lhs: 10, nrhs: 3),
        (lhs: 10, nrhs: 3),
        (lhs: 10, nrhs: 3),
        (lhs: 10, nrhs: 1),
        (lhs: 11, nrhs: 1),
        (lhs: 11, nrhs: 1),
        (lhs: 11, nrhs: 1),
        (lhs: 10, nrhs: 1),
    ]

    // Stack

    var yyStack: [(stateOrRule: CitronStateOrRule , symbolCode: CitronSymbolCode, symbol: CitronSymbol)]  = [
        (stateOrRule: .state(0), symbolCode: 0, symbol: .yyBaseOfStack)
    ]
    var maxStackSize: Int? = nil
    // Tracing

    var isTracingEnabled: Bool = false
    let yySymbolName: [String] = [
        "$",                   "ADD",                 "SUB",                 "MUL",         
        "DIV",                 "INT",                 "FLOAT",               "BOOL",        
        "IDENTIFIER",          "root",                "expr",                "const",       
    ]
    let yyRuleText: [String] = [
        /*   0 */ "root ::= expr(a)",
        /*   1 */ "expr ::= expr(a) ADD expr(b)",
        /*   2 */ "expr ::= expr(a) SUB expr(b)",
        /*   3 */ "expr ::= expr(a) MUL expr(b)",
        /*   4 */ "expr ::= expr(a) DIV expr(b)",
        /*   5 */ "expr ::= const(a)",
        /*   6 */ "const ::= INT(a)",
        /*   7 */ "const ::= FLOAT(a)",
        /*   8 */ "const ::= BOOL(a)",
        /*   9 */ "expr ::= IDENTIFIER(a)",
    ]

    // Function definitions

    func yyTokenToSymbol(_ token: CitronToken) -> CitronSymbol {
        return .yy0(token)
    }

    func yyInvokeCodeBlockForRule(ruleNumber: CitronRuleNumber) throws -> CitronSymbol {
        switch (ruleNumber) {
        case 0: /* root ::= expr(a) */
            func codeBlockForRule00(a: Expr) throws -> Expr {
    return a
 }
            if case .yy12(let a) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy12(try codeBlockForRule00(a: a))
            }
        case 1: /* expr ::= expr(a) ADD expr(b) */
            func codeBlockForRule01(a: Expr, b: Expr) throws -> Expr {
    return .arithOps(ops: .add, args: [a, b])
 }
            if case .yy12(let a) = yySymbolOnStack(distanceFromTop: 2),
               case .yy12(let b) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy12(try codeBlockForRule01(a: a, b: b))
            }
        case 2: /* expr ::= expr(a) SUB expr(b) */
            func codeBlockForRule02(a: Expr, b: Expr) throws -> Expr {
    return .arithOps(ops: .sub, args: [a, b])
 }
            if case .yy12(let a) = yySymbolOnStack(distanceFromTop: 2),
               case .yy12(let b) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy12(try codeBlockForRule02(a: a, b: b))
            }
        case 3: /* expr ::= expr(a) MUL expr(b) */
            func codeBlockForRule03(a: Expr, b: Expr) throws -> Expr {
    return .arithOps(ops: .mul, args: [a, b])
 }
            if case .yy12(let a) = yySymbolOnStack(distanceFromTop: 2),
               case .yy12(let b) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy12(try codeBlockForRule03(a: a, b: b))
            }
        case 4: /* expr ::= expr(a) DIV expr(b) */
            func codeBlockForRule04(a: Expr, b: Expr) throws -> Expr {
    return .arithOps(ops: .div, args: [a, b])
 }
            if case .yy12(let a) = yySymbolOnStack(distanceFromTop: 2),
               case .yy12(let b) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy12(try codeBlockForRule04(a: a, b: b))
            }
        case 5: /* expr ::= const(a) */
            func codeBlockForRule05(a: Const) throws -> Expr {
    return .const(const: a)
 }
            if case .yy8(let a) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy12(try codeBlockForRule05(a: a))
            }
        case 6: /* const ::= INT(a) */
            func codeBlockForRule06(a: Token) throws -> Const {
    return .integer(a.asInt())
 }
            if case .yy0(let a) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy8(try codeBlockForRule06(a: a))
            }
        case 7: /* const ::= FLOAT(a) */
            func codeBlockForRule07(a: Token) throws -> Const {
    return .float(a.asFloat())
 }
            if case .yy0(let a) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy8(try codeBlockForRule07(a: a))
            }
        case 8: /* const ::= BOOL(a) */
            func codeBlockForRule08(a: Token) throws -> Const {
    return .bool(a.asBool())
 }
            if case .yy0(let a) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy8(try codeBlockForRule08(a: a))
            }
        case 9: /* expr ::= IDENTIFIER(a) */
            func codeBlockForRule09(a: Token) throws -> Expr {
    return .var(variable: Var(rawValue: a.asIdentifier()))
 }
            if case .yy0(let a) = yySymbolOnStack(distanceFromTop: 0) {
                return .yy12(try codeBlockForRule09(a: a))
            }
        default:
            fatalError("Can't invoke code block for rule number \(ruleNumber) - no such rule")
        }
        fatalError("Can't resolve types correctly for invoking code block for rule number \(ruleNumber)")
    }

    private func yySymbolOnStack(distanceFromTop: Int) -> CitronSymbol {
        assert(yyStack.count > distanceFromTop)
        return yyStack[yyStack.count - 1 - distanceFromTop].symbol
    }

    func yyUnwrapResultFromSymbol(_ symbol: CitronSymbol) -> CitronResult {
        if case .yy12(let result) = symbol {
            return result
        } else {
            fatalError("Unexpected mismatch in result type")
        }
    }

}

